version: "3"
services:
  embyserver:
    image: emby/embyserver:latest
    ports:
      - 8096:8096
    volumes:
      - ${EMBY_CONF}:/config
      - /byr/byr:/share
    expose:
        - ${EMBY_PORT}
    environment:
        VIRTUAL_HOST: ${VIRTUAL_HOST}
        LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
        LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        VIRTUAL_PORT: ${EMBY_PORT}


networks:
    default:
        external:
            name: ${NETWORK:-proxy}
