[helpers]

[rust.files]
"rust/.cargo/config" = { type = "symbolic", target = "~/.cargo/config", if = '(is_executable "rustc")'}

[git.files]
"git/.gitconfig" = { type = "symbolic", target = "~/.gitconfig"}

[tmux.files]
"tmux/.tmux.conf" = { type = "symbolic", target = "~/.tmux.conf"}

[zsh]
depends = ["git", "tmux"]

[zsh.files]
"zsh/.zshrc" = { type = "symbolic", target = "~/.zshrc"}
"zsh/.p10k.zsh" = { type = "symbolic", target = "~/.p10k.zsh"}

[ohmyzsh]
depends = ["git", "tmux"]

[ohmyzsh.files]
# "ohmyzsh/.oh-my-zsh" = { type = "symbolic", target = "~/.oh-my-zsh"}
"ohmyzsh/.zshrc" = { type = "symbolic", target = "~/.zshrc"}
"ohmyzsh/.p10k.zsh" = { type = "symbolic", target = "~/.p10k.zsh"}

[zellij.files]
"zellij" = { type = "symbolic", target = "~/.config/zellij" }