[settings]
default_target_type = "symbolic"

[helpers]

[rust.files]
# 'if' conditions require explicit type
"rust/.cargo/config.toml" = { type = "symbolic", target = "~/.cargo/config.toml", if = '(is_executable "rustc")' }

[git.files]
"git/.gitconfig" = "~/.gitconfig"

[tmux.files]
"tmux/.tmux.conf" = "~/.tmux.conf"

[zsh.files]
"zsh/.zshrc" = "~/.zshrc"
"zsh/.p10k.zsh" = "~/.p10k.zsh"

[ohmyzsh.files]
"ohmyzsh/.zshrc" = "~/.zshrc"
"ohmyzsh/.p10k.zsh" = "~/.p10k.zsh"

[zellij.files]
"zellij" = { type = "symbolic", target = "~/.config/zellij", recurse = false }

[nvim.files]
"nvim" = { type = "symbolic", target = "~/.config/nvim", recurse = false }

[lazygit.files]
# 'if' conditions require explicit type
"lazygit/config.yml" = { type = "symbolic", target = "~/.config/lazygit/config.yml", if = '(is_executable "delta")' }

[claude.files]
"claude/settings.json" = "~/.claude/settings.json"
"claude/CLAUDE.md" = "~/.claude/CLAUDE.md"
